---
Name: template-yield
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        YieldHTTPMiddleware: '%$Bigfork\SilverstripeTemplateYield\YieldHTTPMiddleware'
  SilverStripe\View\SSTemplateParser:
    properties:
      closedBlocks:
        section: 'Bigfork\SilverstripeTemplateYield\BlockProvider::sectionClosedTemplate'
        yield: 'Bigfork\SilverstripeTemplateYield\BlockProvider::yieldClosedTemplate'
      openBlocks:
        section: 'Bigfork\SilverstripeTemplateYield\BlockProvider::sectionOpenTemplate'
        yield: 'Bigfork\SilverstripeTemplateYield\BlockProvider::yieldOpenTemplate'
